import assert from 'node:assert';
import { createInput } from '../js/input.js';
const input = createInput();
input._kd({ code: 'KeyW', repeat: false, preventDefault(){} });
input._kd({ code: 'KeyW', repeat: true, preventDefault(){} });
assert.ok(input.isDown('KeyW'));
assert.equal(input.keys.size, 1);
input._kd({ code: 'ArrowRight', repeat: false, preventDefault(){} });
assert.deepEqual(input.aimDir(), { x: 1, y: 0 });
let paused = 0;
input.onPause = () => paused++;
input._kd({ code: 'KeyP', repeat: false, preventDefault(){} });
assert.equal(paused, 1);
input._blur();
assert.equal(input.keys.size, 0);
console.log('input ok');
