import assert from 'node:assert';
import { createWorld } from '../js/entities.js';
import { createRoom } from '../js/room.js';
const layer = { prepend(){}, appendChild(){} };
const world = createWorld({ appendChild(){} });
const room = createRoom(world, layer);
assert.deepEqual(room.waveSizes, [3, 5, 7]);
room.reset();
assert.equal(room.wave, 0);
assert.equal(room.mapName, 'Cour');
assert.ok(world.tilemap && world.tilemap.tiles.length === 475);
assert.ok(world.player.x < 200 && world.player.y < 200, 'player at first spawn');
room.update(0.1);
assert.ok(world.enemies.filter(e => e.active).length > 0);
// wave advance loads next map: kill all, drain spawned
for (const e of world.enemies) e.active = false;
room.spawned = 3;
room.update(0.1);
assert.equal(room.mapName, 'Piliers');
console.log('room ok');
